# 'image' will vary depending on your docker-compose
# project name. You may need to run `docker-compose build web`
# before this works.
bundle:
  image: beatalong_web
  volumes:
    - bundle

web:
  build: .
  env_file: config/.env
  command: bundle exec shotgun --port 3000 --host 0.0.0.0
  volumes:
    - .:/beatalong
  ports:
    - "3000:3000"
  volumes_from:
    - bundle
  links:
    - redis

redis:
  image: redis
  ports:
    - "6379"
